set nocompatible
filetype indent plugin on
syntax on

" show line numbers
" set nu
" https://jeffkreeftmeijer.com/vim-number/
set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

set noshowmode

" do not wrap long lines
set nowrap

set expandtab
set autoindent
set cursorcolumn
set cursorline

set tabstop=4
set shiftwidth=4
set softtabstop=4

" textwidth = 79
set tw=79

" Solarized Theme
set bg=dark

" colorscheme solarized


" Status line stuff
set encoding=utf-8
scriptencoding utf-8
set laststatus=2

"
" vim-plug
"

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
"
"   " Make sure you use single quotes
"
"   " Initialize plugin system
    " Plug 'junegunn/fzf.vim'
    Plug 'saltstack/salt-vim'
    Plug 'stephpy/vim-yaml'
    Plug 'altercation/vim-colors-solarized'
    Plug 'tpope/vim-commentary'
    Plug 'bling/vim-airline'
call plug#end()
